---
title: "News"
---

## 2025

## We're going to Melbourne! :)

Zahle and Hannah will be presented at a day long workshop (run by Bulbulia), on causal inference for psychological scientists. 

Workshop materials are here 👇

- **[2025 November 19]:** Beyond Correlation: A Practical Introduction to Causal Inference in Observational Social Psychology
[link](https://go-bayes.github.io/2025-workshop-ci-sasp/)


## Past Events

- **[2025 August 10-13]:** Workshop on Causal Inferece at the University of San Diego [link](https://go-bayes.github.io/sparcc-day-2/)




### August 2025: William Bier Interdisciplinary Award Lecture

Joseph Bulbulia delivered the William Bier Interdisciplinary Award lecture: "Who Benefits from Religious Attendance? Heterogeneous Causal Effects on Well-being and Cooperation in New Zealand" at 11:30-12:30 in Convention Centre Street Level 208. The William Bier Interdisciplinary Award is presented by the **American Psychological Association Division 36 (Psychology of Religion and Spirituality)**.

---


## 2024

*News archive coming soon...*

---

