#!/bin/bash

# Simple script to set up team photo structure
# Lists all team members and their expected photo filenames

TEAM_DIR="/Users/joseph/GIT/epic-lab/images/team"

echo "📸 EPIC-lab Team Photo Setup"
echo "============================"
echo ""
echo "Expected photo filenames in $TEAM_DIR:"
echo ""
echo "Principal Investigator:"
echo "  - joseph-bulbulia.jpg"
echo ""
echo "Research Fellow:"
echo "  - inkuk-kim.jpg"
echo ""
echo "PhD Students:"
echo "  - jake-ireland.jpg"
echo "  - jesse-auckerman.jpg"
echo ""
echo "Master's Students:"
echo "  - boyang-cao.jpg"
echo "  - hannah-robinson.jpg"
echo "  - zahle-wisely.jpg"
echo ""
echo "Research Assistants:"
echo "  - millie-rea.jpg"
echo ""
echo "Alumni:"
echo "  - johnmark-kempthorn.jpg"
echo "  - bella-chong.jpg"
echo ""
echo "To add photos:"
echo "1. Use the optimization script:"
echo "   ./scripts/optimize-photo.sh /path/to/photo.jpg firstname-lastname"
echo ""
echo "2. Or manually add 400x400px JPG files with the names above"
echo ""
echo "Note: The site will show broken image icons until photos are added."